version: '2'
services:
    broken1-app:
        image: broken1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://broken1-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=broken1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    broken1-mongodb:
        extends:
            file: mongodb.yml
            service: broken1-mongodb
